agent:
  log_level: INFO
  name: Infrastructure AI Agent
  version: 0.1.0
  workspace: /tmp/agent-workspace
aws:
  assume_role_arn: null
  external_id: null
  profile: default
  region: ap-southeast-2
backup_enabled: true
cost:
  budget_limit_monthly: null
  cost_alert_threshold: 0.8
  enable_cost_optimization: true
  spot_instance_usage: true
debug_mode: false
deployment:
  default_strategy: rolling
  deployment_environments:
  - dev
  - staging
  - prod
  rollback_on_failure: true
  timeout_minutes: 30
dry_run: false
github_token: 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
gitlab_token: null
kubernetes:
  cluster_version: '1.28'
  desired_nodes: 2
  enable_auto_scaling: true
  max_nodes: 10
  min_nodes: 1
  node_instance_types:
  - t3.medium
  - t3.large
max_tokens: 4000
model_name: gpt-4
monitoring:
  enable_cloudwatch: true
  enable_grafana: true
  enable_prometheus: true
  log_level: INFO
  retention_days: 30
openai_api_key: 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
security:
  compliance_frameworks:
  - AWS-Well-Architected
  enable_security_scanning: true
  encryption_at_rest: true
  encryption_in_transit: true
  iam_role_prefix: agent-
  root_credential_usage: initial_setup_only
state_persistence: true
temperature: 0.1
